# Generated by Django 5.2.3 on 2025-06-18 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedaladas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_total', models.FloatField()),
                ('distancia_percorrida', models.TextField(blank=True, default='')),
                ('pontos_registrados', models.TextField(blank=True, default='')),
                ('caminho', models.JSONField(blank=True, default=list)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedaladas', to='rotas.rotas')),
            ],
            options={
                'verbose_name': 'Pedalada',
                'verbose_name_plural': 'Pedaladas',
                'ordering': ['tempo_total'],
            },
        ),
    ]
